CI: fail when raw_tables.txt not updated; add instructions on updating (#18)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,19 +10,9 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout base branch
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v3
       with:
-        ref: ${{ github.base_ref }}
-        path: base
-        token: ${{ secrets.GH_TOKEN }}
-
-    - name: Checkout head branch
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.head_ref }}
         path: head
-        token: ${{ secrets.GH_TOKEN }}
 
     - name: Setup Python
       uses: actions/setup-python@v4
@@ -31,43 +21,29 @@ jobs:
 
     - name: Install times-excel-reader
       run: |
+        pip install -U pip
         pip install git+https://github.com/etsap-TIMES/times-excel-reader.git
 
     - name: Run raw_table_summary on TIMES-NZ-Model-Files
       run: |
-        cd head
-        times-excel-reader TIMES-NZ/ --output_dir TIMES-NZ/raw_table_summary/ --only_read
+        times-excel-reader head/TIMES-NZ/ --output_dir head/TIMES-NZ/raw_table_summary/ --only_read
 
-    - name: Display output
+    - name: Check if raw_table_summary is updated
+      id: raw_table_updated
       run: |
         cd head/TIMES-NZ/raw_table_summary
-        cat raw_tables.txt
+        if ! git diff --quiet; then \
+          echo "ERROR: raw_table_summary is not up-to-date."; \
+          echo "The uploaded artifact contains the raw_table_summary for your branch, commit that to pass this check."; \
+          echo "See README for more details."; \
+          exit 1; fi
 
-    - name: Upload output
+    - name: Upload raw_tables.txt
       uses: actions/upload-artifact@v3
+      if: ${{ failure() && steps.raw_table_updated.outcome == 'failure' }}
       with:
-        name: output
+        name: raw_tables
         path: head/TIMES-NZ/raw_table_summary/raw_tables.txt
-
-    - name: Copy raw_tables.txt to base branch
-      run: |
-        mkdir -p base/TIMES-NZ/raw_table_summary
-        cp head/TIMES-NZ/raw_table_summary/raw_tables.txt base/TIMES-NZ/raw_table_summary/raw_tables.txt
-
-    - name: Generate git diff
-      run: |
-        cd base
-        git diff > diff.txt
-
-    - name: Display git diff
-      run: |
-        cat base/diff.txt
-
-    - name: Upload git diff
-      uses: actions/upload-artifact@v3
-      with:
-        name: diff
-        path: base/diff.txt
 
     - name: Run times-excel-reader on TIMES-NZ-Model-Files
       run: |
